flat: flat.cpp gameobject.cpp gameobject.h physics.cpp physics.h planeobject.cpp planeobject.h sphereobject.cpp sphereobject.h vectorobject.cpp vectorobject.h
	g++ -o flat vectorobject.cpp physics.cpp planeobject.cpp gameobject.cpp sphereobject.cpp playerobject.cpp flat.cpp -lglut -lGLU -lGL -lm
